// Category names are database content — seeded once, in Spanish, by
// `plaza_backend/seeders/data/categories.data.seeders.js` — and there is no
// admin flow yet to add a category outside that file. Rather than change the
// API to carry three languages for a table that today only ever grows by
// editing code, this is a frontend lookup table keyed by the same `slug` the
// backend already sends, translating what the backend cannot yet.
//
// Deliberately not exhaustive-proof: a new category added to the seeder
// without an entry here just shows its Spanish name in English and
// Portuguese too, the same way an untranslated string anywhere else would —
// not a crash, a gap to fill next time this file is touched.
export const CATEGORY_LABELS = {
  tecnologia: { en: 'Electronics', pt: 'Eletrônicos' },
  'tecnologia-celulares-y-accesorios': { en: 'Phones & accessories', pt: 'Celulares e acessórios' },
  'tecnologia-computadores-y-portatiles': { en: 'Computers & laptops', pt: 'Computadores e notebooks' },
  'tecnologia-televisores-y-audio': { en: 'TVs & audio', pt: 'TVs e áudio' },
  'tecnologia-consolas-y-videojuegos': { en: 'Consoles & video games', pt: 'Consoles e video games' },
  'tecnologia-camaras-y-fotografia': { en: 'Cameras & photography', pt: 'Câmeras e fotografia' },
  'tecnologia-accesorios-de-computador': { en: 'Computer accessories', pt: 'Acessórios de computador' },
  'tecnologia-almacenamiento': { en: 'Storage', pt: 'Armazenamento' },
  'tecnologia-componentes-y-repuestos': { en: 'Components & parts', pt: 'Componentes e peças' },

  'hogar-y-muebles': { en: 'Home & Furniture', pt: 'Casa e móveis' },
  'hogar-y-muebles-muebles': { en: 'Furniture', pt: 'Móveis' },
  'hogar-y-muebles-colchones-y-descanso': { en: 'Mattresses & sleep', pt: 'Colchões e descanso' },
  'hogar-y-muebles-cocina-y-comedor': { en: 'Kitchen & dining', pt: 'Cozinha e sala de jantar' },
  'hogar-y-muebles-bano': { en: 'Bathroom', pt: 'Banheiro' },
  'hogar-y-muebles-decoracion': { en: 'Decor', pt: 'Decoração' },
  'hogar-y-muebles-iluminacion': { en: 'Lighting', pt: 'Iluminação' },
  'hogar-y-muebles-organizacion-y-almacenamiento': { en: 'Organization & storage', pt: 'Organização e armazenamento' },
  'hogar-y-muebles-jardin-y-exteriores': { en: 'Garden & outdoor', pt: 'Jardim e área externa' },

  moda: { en: 'Fashion', pt: 'Moda' },
  'moda-ropa-de-mujer': { en: "Women's clothing", pt: 'Roupas femininas' },
  'moda-ropa-de-hombre': { en: "Men's clothing", pt: 'Roupas masculinas' },
  'moda-calzado': { en: 'Footwear', pt: 'Calçados' },
  'moda-bolsos-y-carteras': { en: 'Bags & purses', pt: 'Bolsas e carteiras' },
  'moda-relojes-y-joyeria': { en: 'Watches & jewelry', pt: 'Relógios e joias' },
  'moda-gafas': { en: 'Eyewear', pt: 'Óculos' },
  'moda-ropa-infantil': { en: "Kids' clothing", pt: 'Roupas infantis' },
  'moda-accesorios': { en: 'Accessories', pt: 'Acessórios' },

  electrodomesticos: { en: 'Appliances', pt: 'Eletrodomésticos' },
  'electrodomesticos-refrigeracion': { en: 'Refrigeration', pt: 'Refrigeração' },
  'electrodomesticos-lavado-y-secado': { en: 'Washing & drying', pt: 'Lavagem e secagem' },
  'electrodomesticos-coccion': { en: 'Cooking', pt: 'Cozimento' },
  'electrodomesticos-pequenos-electrodomesticos': { en: 'Small appliances', pt: 'Pequenos eletrodomésticos' },
  'electrodomesticos-climatizacion': { en: 'Climate control', pt: 'Climatização' },
  'electrodomesticos-aspiradoras-y-limpieza': { en: 'Vacuums & cleaning', pt: 'Aspiradores e limpeza' },

  'belleza-y-cuidado-personal': { en: 'Beauty & Personal Care', pt: 'Beleza e cuidado pessoal' },
  'belleza-y-cuidado-personal-maquillaje': { en: 'Makeup', pt: 'Maquiagem' },
  'belleza-y-cuidado-personal-cuidado-de-la-piel': { en: 'Skin care', pt: 'Cuidados com a pele' },
  'belleza-y-cuidado-personal-cuidado-del-cabello': { en: 'Hair care', pt: 'Cuidados com o cabelo' },
  'belleza-y-cuidado-personal-perfumes': { en: 'Perfumes', pt: 'Perfumes' },
  'belleza-y-cuidado-personal-afeitado-y-depilacion': { en: 'Shaving & hair removal', pt: 'Barba e depilação' },
  'belleza-y-cuidado-personal-higiene-personal': { en: 'Personal hygiene', pt: 'Higiene pessoal' },

  'deportes-y-aire-libre': { en: 'Sports & Outdoors', pt: 'Esportes e ar livre' },
  'deportes-y-aire-libre-ciclismo': { en: 'Cycling', pt: 'Ciclismo' },
  'deportes-y-aire-libre-fitness-y-musculacion': { en: 'Fitness & strength training', pt: 'Fitness e musculação' },
  'deportes-y-aire-libre-camping-y-montanismo': { en: 'Camping & hiking', pt: 'Camping e montanhismo' },
  'deportes-y-aire-libre-futbol': { en: 'Soccer', pt: 'Futebol' },
  'deportes-y-aire-libre-running': { en: 'Running', pt: 'Corrida' },
  'deportes-y-aire-libre-deportes-acuaticos': { en: 'Water sports', pt: 'Esportes aquáticos' },
  'deportes-y-aire-libre-suplementos-deportivos': { en: 'Sports supplements', pt: 'Suplementos esportivos' },

  'vehiculos-y-repuestos': { en: 'Vehicles & Parts', pt: 'Veículos e peças' },
  'vehiculos-y-repuestos-repuestos-de-carros': { en: 'Car parts', pt: 'Peças de carros' },
  'vehiculos-y-repuestos-repuestos-de-motos': { en: 'Motorcycle parts', pt: 'Peças de motos' },
  'vehiculos-y-repuestos-accesorios-y-tuning': { en: 'Accessories & tuning', pt: 'Acessórios e tuning' },
  'vehiculos-y-repuestos-llantas': { en: 'Tires', pt: 'Pneus' },
  'vehiculos-y-repuestos-audio-para-vehiculos': { en: 'Car audio', pt: 'Som automotivo' },
  'vehiculos-y-repuestos-herramientas-de-taller': { en: 'Workshop tools', pt: 'Ferramentas de oficina' },

  'herramientas-y-construccion': { en: 'Tools & Construction', pt: 'Ferramentas e construção' },
  'herramientas-y-construccion-herramientas-electricas': { en: 'Power tools', pt: 'Ferramentas elétricas' },
  'herramientas-y-construccion-herramientas-manuales': { en: 'Hand tools', pt: 'Ferramentas manuais' },
  'herramientas-y-construccion-materiales-de-construccion': { en: 'Building materials', pt: 'Materiais de construção' },
  'herramientas-y-construccion-pinturas': { en: 'Paints', pt: 'Tintas' },
  'herramientas-y-construccion-seguridad-industrial': { en: 'Industrial safety', pt: 'Segurança industrial' },
  'herramientas-y-construccion-electricidad-y-plomeria': { en: 'Electrical & plumbing', pt: 'Elétrica e encanamento' },

  'bebes-y-ninos': { en: 'Baby & Kids', pt: 'Bebês e crianças' },
  'bebes-y-ninos-coches-y-sillas': { en: 'Strollers & car seats', pt: 'Carrinhos e cadeirinhas' },
  'bebes-y-ninos-alimentacion': { en: 'Feeding', pt: 'Alimentação' },
  'bebes-y-ninos-panales-y-aseo': { en: 'Diapers & care', pt: 'Fraldas e higiene' },
  'bebes-y-ninos-juguetes': { en: 'Toys', pt: 'Brinquedos' },
  'bebes-y-ninos-ropa-de-bebe': { en: 'Baby clothing', pt: 'Roupas de bebê' },
  'bebes-y-ninos-habitacion-infantil': { en: 'Nursery', pt: 'Quarto infantil' },

  'alimentos-y-bebidas': { en: 'Food & Beverages', pt: 'Alimentos e bebidas' },
  'alimentos-y-bebidas-cafe-y-te': { en: 'Coffee & tea', pt: 'Café e chá' },
  'alimentos-y-bebidas-despensa': { en: 'Pantry', pt: 'Despensa' },
  'alimentos-y-bebidas-snacks-y-dulces': { en: 'Snacks & candy', pt: 'Salgadinhos e doces' },
  'alimentos-y-bebidas-bebidas': { en: 'Beverages', pt: 'Bebidas' },
  'alimentos-y-bebidas-productos-organicos': { en: 'Organic products', pt: 'Produtos orgânicos' },
  'alimentos-y-bebidas-reposteria': { en: 'Baking', pt: 'Confeitaria' },

  mascotas: { en: 'Pets', pt: 'Animais de estimação' },
  'mascotas-perros': { en: 'Dogs', pt: 'Cães' },
  'mascotas-gatos': { en: 'Cats', pt: 'Gatos' },
  'mascotas-aves': { en: 'Birds', pt: 'Aves' },
  'mascotas-peces-y-acuarios': { en: 'Fish & aquariums', pt: 'Peixes e aquários' },
  'mascotas-pequenas-mascotas': { en: 'Small pets', pt: 'Pequenos animais' },

  'salud-y-bienestar': { en: 'Health & Wellness', pt: 'Saúde e bem-estar' },
  'salud-y-bienestar-cuidado-de-la-salud': { en: 'Health care', pt: 'Cuidados de saúde' },
  'salud-y-bienestar-suplementos-y-vitaminas': { en: 'Supplements & vitamins', pt: 'Suplementos e vitaminas' },
  'salud-y-bienestar-equipos-medicos': { en: 'Medical equipment', pt: 'Equipamentos médicos' },
  'salud-y-bienestar-movilidad-y-ortopedia': { en: 'Mobility & orthopedics', pt: 'Mobilidade e ortopedia' },

  'arte-y-artesanias': { en: 'Arts & Crafts', pt: 'Arte e artesanato' },
  'arte-y-artesanias-artesania-colombiana': { en: 'Colombian crafts', pt: 'Artesanato colombiano' },
  'arte-y-artesanias-materiales-de-arte': { en: 'Art supplies', pt: 'Materiais de arte' },
  'arte-y-artesanias-manualidades': { en: 'Crafts', pt: 'Trabalhos manuais' },
  'arte-y-artesanias-instrumentos-musicales': { en: 'Musical instruments', pt: 'Instrumentos musicais' },
  'arte-y-artesanias-coleccionables': { en: 'Collectibles', pt: 'Colecionáveis' },

  'libros-y-papeleria': { en: 'Books & Stationery', pt: 'Livros e papelaria' },
  'libros-y-papeleria-libros': { en: 'Books', pt: 'Livros' },
  'libros-y-papeleria-utiles-escolares': { en: 'School supplies', pt: 'Material escolar' },
  'libros-y-papeleria-oficina': { en: 'Office', pt: 'Escritório' },
  'libros-y-papeleria-revistas-y-comics': { en: 'Magazines & comics', pt: 'Revistas e quadrinhos' },

  /* servicios: el otro pasillo, mismo criterio - la clave es el slug que ya manda la API */
  'construccion-y-reformas': { en: 'Building & Renovation', pt: 'Construção e reformas' },
  'construccion-y-reformas-plomeria': { en: 'Plumbing', pt: 'Encanamento' },
  'construccion-y-reformas-electricidad': { en: 'Electrical work', pt: 'Elétrica' },
  'construccion-y-reformas-pintura': { en: 'Painting', pt: 'Pintura' },
  'construccion-y-reformas-albanileria': { en: 'Masonry', pt: 'Alvenaria' },
  'construccion-y-reformas-carpinteria': { en: 'Carpentry', pt: 'Carpintaria' },
  'construccion-y-reformas-cerrajeria': { en: 'Locksmithing', pt: 'Chaveiro' },
  'construccion-y-reformas-impermeabilizacion': { en: 'Waterproofing', pt: 'Impermeabilização' },
  'construccion-y-reformas-drywall-y-acabados': { en: 'Drywall & finishes', pt: 'Drywall e acabamentos' },
  'hogar-y-limpieza': { en: 'Home & Cleaning', pt: 'Casa e limpeza' },
  'hogar-y-limpieza-aseo-por-horas': { en: 'Cleaning by the hour', pt: 'Limpeza por hora' },
  'hogar-y-limpieza-limpieza-profunda': { en: 'Deep cleaning', pt: 'Limpeza pesada' },
  'hogar-y-limpieza-lavado-de-muebles': { en: 'Upholstery cleaning', pt: 'Lavagem de estofados' },
  'hogar-y-limpieza-jardineria': { en: 'Gardening', pt: 'Jardinagem' },
  'hogar-y-limpieza-control-de-plagas': { en: 'Pest control', pt: 'Controle de pragas' },
  'hogar-y-limpieza-lavanderia-y-planchado': { en: 'Laundry & ironing', pt: 'Lavanderia e passadoria' },
  'cuidado-de-personas': { en: 'Care', pt: 'Cuidado de pessoas' },
  'cuidado-de-personas-nineras': { en: 'Childminders', pt: 'Babás' },
  'cuidado-de-personas-cuidado-de-adultos-mayores': { en: 'Elderly care', pt: 'Cuidado de idosos' },
  'cuidado-de-personas-acompanamiento-en-casa': { en: 'Home companionship', pt: 'Acompanhamento em casa' },
  'cuidado-de-personas-enfermeria-a-domicilio': { en: 'Home nursing', pt: 'Enfermagem a domicílio' },
  'cuidado-de-personas-cuidado-de-personas-con-discapacidad': { en: 'Disability care', pt: 'Cuidado de pessoas com deficiência' },
  'reparaciones-y-tecnicos': { en: 'Repairs & Technicians', pt: 'Consertos e técnicos' },
  'reparaciones-y-tecnicos-electrodomesticos': { en: 'Appliances', pt: 'Eletrodomésticos' },
  'reparaciones-y-tecnicos-aire-acondicionado-y-neveras': { en: 'Air conditioning & fridges', pt: 'Ar-condicionado e geladeiras' },
  'reparaciones-y-tecnicos-computadores': { en: 'Computers', pt: 'Computadores' },
  'reparaciones-y-tecnicos-celulares': { en: 'Phones', pt: 'Celulares' },
  'reparaciones-y-tecnicos-televisores-y-audio': { en: 'TVs & audio', pt: 'TVs e áudio' },
  'reparaciones-y-tecnicos-bicicletas': { en: 'Bicycles', pt: 'Bicicletas' },
  'clases-y-tutorias': { en: 'Lessons & Tutoring', pt: 'Aulas e reforço' },
  'clases-y-tutorias-refuerzo-escolar': { en: 'School tutoring', pt: 'Reforço escolar' },
  'clases-y-tutorias-idiomas': { en: 'Languages', pt: 'Idiomas' },
  'clases-y-tutorias-musica': { en: 'Music', pt: 'Música' },
  'clases-y-tutorias-matematicas': { en: 'Maths', pt: 'Matemática' },
  'clases-y-tutorias-preparacion-de-examenes': { en: 'Exam preparation', pt: 'Preparação para provas' },
  'clases-y-tutorias-informatica': { en: 'Computing', pt: 'Informática' },
  'belleza-y-bienestar': { en: 'Beauty & Wellbeing', pt: 'Beleza e bem-estar' },
  'belleza-y-bienestar-peluqueria-a-domicilio': { en: 'Home hairdressing', pt: 'Cabeleireiro a domicílio' },
  'belleza-y-bienestar-manicura-y-pedicura': { en: 'Manicure & pedicure', pt: 'Manicure e pedicure' },
  'belleza-y-bienestar-maquillaje': { en: 'Make-up', pt: 'Maquiagem' },
  'belleza-y-bienestar-masajes': { en: 'Massage', pt: 'Massagem' },
  'belleza-y-bienestar-entrenamiento-personal': { en: 'Personal training', pt: 'Personal trainer' },
  'belleza-y-bienestar-nutricion': { en: 'Nutrition', pt: 'Nutrição' },
  'eventos': { en: 'Events', pt: 'Eventos' },
  'eventos-fotografia': { en: 'Photography', pt: 'Fotografia' },
  'eventos-video': { en: 'Video', pt: 'Vídeo' },
  'eventos-catering': { en: 'Catering', pt: 'Buffet' },
  'eventos-musica-en-vivo': { en: 'Live music', pt: 'Música ao vivo' },
  'eventos-decoracion': { en: 'Decoration', pt: 'Decoração' },
  'eventos-meseros-y-logistica': { en: 'Waiting staff & logistics', pt: 'Garçons e logística' },
  'eventos-animacion-infantil': { en: 'Children\'s entertainment', pt: 'Animação infantil' },
  'transporte-y-mudanzas': { en: 'Transport & Removals', pt: 'Transporte e mudanças' },
  'transporte-y-mudanzas-mudanzas': { en: 'House removals', pt: 'Mudanças' },
  'transporte-y-mudanzas-acarreos': { en: 'Haulage', pt: 'Fretes' },
  'transporte-y-mudanzas-mensajeria': { en: 'Courier', pt: 'Entregas' },
  'transporte-y-mudanzas-conductor': { en: 'Driver', pt: 'Motorista' },
  'servicios-mascotas': { en: 'Pets', pt: 'Animais de estimação' },
  'servicios-mascotas-paseo-de-perros': { en: 'Dog walking', pt: 'Passeio com cães' },
  'servicios-mascotas-guarderia': { en: 'Day boarding', pt: 'Creche' },
  'servicios-mascotas-peluqueria-canina': { en: 'Dog grooming', pt: 'Banho e tosa' },
  'servicios-mascotas-adiestramiento': { en: 'Training', pt: 'Adestramento' },
  'servicios-mascotas-veterinaria-a-domicilio': { en: 'Home vet visits', pt: 'Veterinário a domicílio' },
  'servicios-profesionales': { en: 'Professional Services', pt: 'Serviços profissionais' },
  'servicios-profesionales-contabilidad': { en: 'Accounting', pt: 'Contabilidade' },
  'servicios-profesionales-asesoria-legal': { en: 'Legal advice', pt: 'Assessoria jurídica' },
  'servicios-profesionales-diseno-grafico': { en: 'Graphic design', pt: 'Design gráfico' },
  'servicios-profesionales-desarrollo-web': { en: 'Web development', pt: 'Desenvolvimento web' },
  'servicios-profesionales-traduccion': { en: 'Translation', pt: 'Tradução' },
  'servicios-profesionales-marketing-digital': { en: 'Digital marketing', pt: 'Marketing digital' },
  'servicios-profesionales-arquitectura': { en: 'Architecture', pt: 'Arquitetura' },
  'confeccion-y-arreglos': { en: 'Tailoring & Alterations', pt: 'Costura e ajustes' },
  'confeccion-y-arreglos-arreglos-de-ropa': { en: 'Clothing alterations', pt: 'Ajustes de roupa' },
  'confeccion-y-arreglos-confeccion-a-medida': { en: 'Made to measure', pt: 'Sob medida' },
  'confeccion-y-arreglos-tapiceria': { en: 'Upholstery', pt: 'Tapeçaria' },
  'confeccion-y-arreglos-bordado-y-estampado': { en: 'Embroidery & printing', pt: 'Bordado e estamparia' },
  'servicios-vehiculos': { en: 'Vehicles', pt: 'Veículos' },
  'servicios-vehiculos-mecanica-a-domicilio': { en: 'Mobile mechanic', pt: 'Mecânico a domicílio' },
  'servicios-vehiculos-latoneria-y-pintura': { en: 'Bodywork & paint', pt: 'Funilaria e pintura' },
  'servicios-vehiculos-lavado-de-vehiculos': { en: 'Vehicle washing', pt: 'Lavagem de veículos' },
  'servicios-vehiculos-instalacion-de-accesorios': { en: 'Accessory fitting', pt: 'Instalação de acessórios' },
}
